import { type StoreStateType } from "../types";

const initialState: StoreStateType = {
  rfId: "",
  domNode: null,
  minZoom: 0.5,
  maxZoom: 2,
  nodes: [],
  edges: [],
  nodesControlled: false,
  edgesControlled: false,
  nodesInitialized: false,
  nodeLookup: new Map(),
  edgeLookup: new Map(),
  nodeTypes: {} as StoreStateType["nodeTypes"],
  edgeTypes: {} as StoreStateType["edgeTypes"],
  onNodesChange: null,
  onEdgesChange: null,
  defaultViewport: { x: 0, y: 0, zoom: 1 },
  panZoom: null,
  nodesConnectable: true,
  nodesDraggable: true,
  nodesSelectable: true,
  zoomOnScroll: true,
  zoomOnPinch: true,
  zoomOnDoubleClick: true,
  panOnScroll: false,
  preventScrolling: true,
  transform: [0, 0, 1],
  mousePosition: { x: 0, y: 0 },
  selectedPoint: null,
  isPanning: false,
};

export default initialState;
